version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: eg-mobile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - EG_BASE_URL=${EG_BASE_URL:-http://localhost:80} 
    restart: unless-stopped 