# fly.toml app configuration file generated for eg-mobile-staging on 2025-03-26T16:22:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eg-mobile-staging'
primary_region = 'bos'

[build]
  dockerfile='Dockerfile'

[env]
  stage="production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
